- alias: modem
  id: '1507552514444'
  trigger:
    platform: state
    entity_id: binary_sensor.modem
    from: 'on'
    to: 'off'
  action:
    service: notify.Telegram
    data:
      message: "\u041C\u043E\u0434\u0435\u043C\u0430 \u0432 \u0413\u043E\u0440\u043D\
        \u0438 \u0412\u043E\u0434\u0435\u043D \u0441\u0435 \u0440\u0430\u0437\u043A\
        \u0430\u0447\u0438"
- alias: Check if user is at home and notify
  id: '1507552517531'
  trigger:
    platform: state
    entity_id: device_tracker.georgi_coolpad
    from: not_home
    to: home
  action:
    service: notify.Telegram
    data:
      message: "\u0413\u0435\u043E\u0440\u0433\u0438 \u0441\u0438 \u0435 \u0432\u043A\
        \u044A\u0449\u0438"
- alias: ChargedBattery
  id: '1507552517534'
  trigger:
    platform: numeric_state
    entity_id: sensor.battery_georgi_coolpad
    above: 99
  action:
    service: notify.Telegram
    data_template:
      title: "\u0411\u0430\u0442\u0435\u0440\u0438\u044F\u0442\u0430 \u043D\u0430\
        \ Coolpad \u0435 \u0437\u0430\u0440\u0435\u0434\u0435\u043D\u0430"
- alias: Update notifications
  id: '1507552517548'
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
    service: notify.Telegram
    data:
      message: "\u0418\u043C\u0430 \u043D\u043E\u0432\u0430 \u0432\u0435\u0440\u0441\
        \u0438\u0430 \u043D\u0430 Home Assistant"
