homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret haname
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Sofia
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

#http:
  # Uncomment this to add a password (recommended!)
    # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

ifttt:
  key: !secret ifttt

# Discover some devices automatically
discovery:
    
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#group: !include conf/groups.yaml  
group: !include_dir_merge_named conf/group
automation: !include automations.yaml
#automation: !include conf/automation.yaml
# sensor: !include conf/sensors.yaml
sensor: !include_dir_merge_list conf/sensor
switch: !include conf/switches.yaml
device_tracker: !include conf/device_tracker.yaml
script: !include conf/scripts.yaml
light: !include conf/lights.yaml
media_player: !include conf/media_players.yaml
notify: !include conf/notify.yaml
http: !include conf/http.yaml
mqtt: !include conf/mqtts.yaml
shell_command: !include conf/shell_commands.yaml
weblink: !include conf/weblinks.yaml
camera: !include conf/cameras.yaml
binary_sensor: !include_dir_merge_list conf/binary_sensor
zone: !include conf/zones.yaml

panel_custom:   
  - name: floorplan
    sidebar_title: SKYNET
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

# binary_sensor: !include conf/binary_sensors.yaml
telegram_bot:
  platform: polling
  api_key: !secret telegram_api_key
  allowed_chat_ids:
    - !secret telegram_chat_id1


