

- platform: template
  sensors:
    battery_georgi_coolpad:
      value_template: '{{ states.device_tracker.georgi_coolpad.attributes.battery|default(0) }}'
      icon_template: >
        {% set battery_level = states.device_tracker.georgi_coolpad.attributes.battery|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    battery_plamena_elephone:
            value_template: '{{ states.device_tracker.plamena_elephone.attributes.battery|default(0) }}'
            icon_template: >
              {% set battery_level = states.device_tracker.plamena_elephone.attributes.battery|default(0)|int %}
              {% set battery_round = (battery_level / 10) |int * 10 %}
              {% if battery_round >= 100 %}
                mdi:battery
              {% elif battery_round > 0 %}
                mdi:battery-{{ battery_round }}
              {% else %}
                mdi:battery-alert
              {% endif %}
