################DUMMY TEMP SENSORS##########################
- platform: mqtt
  state_topic: dummy/floorplan/sensors
  name: temp_hall
- platform: mqtt
  state_topic: dummy/floorplan/sensors
  name: temp_bedroom_1
- platform: mqtt
  state_topic: dummy/floorplan/sensors
  name: temp_bathroom
- platform: mqtt
  state_topic: dummy/floorplan/sensors
  name: temp_bedroom_2
- platform: mqtt
  state_topic: dummy/floorplan/sensors
  name: temp_kitchen
- platform: mqtt
  state_topic: dummy/floorplan/sensors
  name: temp_entrance
