- platform: braviatv
  name: sonytv
  host: 192.168.13.13

- platform: cast
  host: 192.168.13.13

- platform: plex
  name: plex
  show_all_controls: true
  use_episode_art: true
  use_custom_entity_ids: true

- platform: kodi
  host: 192.168.13.13
  name: Kodi Sony

- platform: universal
  name: skyplayer
  children:
    - media_player.kodi_sony
    - media_player.sonytv
    - media_player.plex

